FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY ControleEstoque.sln ./
COPY ControleEstoque/ControleEstoque.csproj ./ControleEstoque/
COPY ControleEstoque.Migrator/ControleEstoque.Migrator.csproj ./ControleEstoque.Migrator/
RUN dotnet restore ControleEstoque.Migrator/ControleEstoque.Migrator.csproj

COPY ControleEstoque/ ./ControleEstoque/
COPY ControleEstoque.Migrator/ ./ControleEstoque.Migrator/
RUN dotnet build ControleEstoque.Migrator/ControleEstoque.Migrator.csproj -c Release --no-restore

COPY docker/migrate-entrypoint.sh /migrate-entrypoint.sh
RUN sed -i 's/\r$//' /migrate-entrypoint.sh && chmod +x /migrate-entrypoint.sh

ENTRYPOINT ["sh", "/migrate-entrypoint.sh"]
